version: "3.0"

services:
  app:
    image: martialblog/limesurvey:5-apache
    restart: always
    volumes:
      - surveys:/var/www/html/upload/surveys
    environment:
      - "DB_HOST=db"
    links:
      - db
    depends_on:
      - db
    networks:
      - frontend
      - backend

  db:
    image: mariadb:10.6
    restart: always
    environment:
      - "MYSQL_USER=limesurvey"
      - "MYSQL_DATABASE=limesurvey"
    networks:
      - backend

volumes:
  surveys:

networks:
  frontend:
  backend:
    internal: true
